- src/main/java/com/dart/entity/Amenity.java
> Updated columns, getters, and setters

- src/main/java/com/dart/entity/Amenity.java
- src/main/java/com/dart/entity/Station.java
> Updated all tables to be singular

- src/main/java/com/dart/entity/StationColor.java
> Added StationColor Entity Class

- .gitignore
- src/main/java/com/dart/entity/Amenity.java
- src/main/java/com/dart/entity/AmenityId.java
- src/main/java/com/dart/entity/PointOfInterest.java
- src/main/java/com/dart/entity/Station.java
- src/main/java/com/dart/entity/StationColor.java
- src/main/java/com/dart/entity/StationColorId.java
- src/main/java/com/dart/entity/StationConnection.java
- src/main/java/com/dart/entity/StationConnectionId.java
> Created new classes and updated relationships

- pom.xml
Updated pom.xml file to allow SQL connection. Closes #27.
> Updated pom.xml file.

- src/main/resources/application.properties
> Switched application.properties to use environment variables.

- src/main/java/com/dart/explore/service/StationService.java
- src/main/java/com/dart/explore/service/StationServiceImpl.java
Wrote service layer interface for MVP and added dummy implementation. Actual implementation will be created in future issue. Closes #41.
> Added service layer interface for MVP.

- src/main/java/com/dart/explore/entity/Color.java
- src/main/java/com/dart/explore/entity/StationColor.java
> Defined station color in its own file and added getter/setter method.

- src/main/resources/MySQL_init.sql
- src/main/resources/Postgres_init.sql
Output now matches diagram.
+--------+------+----------+------------------+---------+------+------------+
| poi_id | name | location | walking_distance | pic_url | type | station_id |
+--------+------+----------+------------------+---------+------+------------+
|      1 | PA1  | NULL     |             NULL | NULL    | NULL |          1 |
|      2 | PB1  | NULL     |             NULL | NULL    | NULL |          2 |
|      3 | PC1  | NULL     |             NULL | NULL    | NULL |          3 |
|      4 | PD1  | NULL     |             NULL | NULL    | NULL |          4 |
|      5 | PE1  | NULL     |             NULL | NULL    | NULL |          5 |
|      6 | PE1  | NULL     |             NULL | NULL    | NULL |          5 |
|      7 | PF1  | NULL     |             NULL | NULL    | NULL | …
> Fixed poi table to match data in diagram.

- src/main/resources/MySQL_init.sql
- src/main/resources/Postgres_init.sql
> PE1 to PE2

- src/main/java/com/dart/explore/entity/Station.java
> update colors to color

- src/main/java/com/dart/explore/controller/StationController.java
- src/main/java/com/dart/explore/repository/PointOfInterestRepository.java
- src/main/java/com/dart/explore/repository/StationRepository.java
- src/main/java/com/dart/explore/service/StationService.java
- src/main/java/com/dart/explore/service/StationServiceImpl.java
Wrote the required boilerplate. The functions are mapped as following:
List<PointOfInterest> getPOIs(List<Amenity> amenities) -> /api/poi
List<Station> getStationsByLine(StationColor color) -> /api/station/{line}
List<PointOfInterest> getPOIsByStation(String stationName) -> /api/poi/{station}
List<PointOfInterest> getPOIsAtStation(String stationName, List<Amenity> amenities) -> /api/poi/{station}
The last two get probably be better distinguished and am open to input. Can discuss on the next call.
> Wrote boilerplate for service and api layer.

- .github/workflows/build.yml
This is also to test if the new workflows are working correctly.
> removed listing files in target

- src/main/java/com/dart/explore/entity/PointOfInterest.java
- src/main/java/com/dart/explore/entity/Station.java
> Updated cascading options where sensible

- pom.xml
- src/main/java/com/dart/explore/controller/StationController.java
- src/main/java/com/dart/explore/security/ApiKeyFilter.java
- src/main/java/com/dart/explore/security/SecurityConfig.java
closes #129 
* Created Security Directory
* Created ApiKeyFilter and SecurityConfig package
> Added security packages to implement API key

- src/main/java/com/dart/explore/exception/DartExploreException.java
- src/main/java/com/dart/explore/utility/ErrorInfo.java
- src/main/java/com/dart/explore/utility/ExceptionControllerAdvice.java
> Added ExceptionHandler

- .gitignore
- src/main/java/com/dart/explore/utility/ExceptionControllerAdvice.java
- src/main/resources/application.properties
> Added logging to file.

- src/main/java/com/dart/explore/dto/PointOfInterestDTO.java
Closes #148. I introduced this bug during #147.
> Fixed error in POI creation.

- .gitignore
- src/main/java/com/dart/explore/utility/ExceptionControllerAdvice.java
> Bean validation messages now show up in response.

- .github/workflows/integrationTests.yml
- pom.xml
- src/main/java/com/dart/explore/controller/ReadController.java
- src/main/java/com/dart/explore/dto/StationDTO.java
- src/main/java/com/dart/explore/repository/PointOfInterestRepository.java
- src/main/java/com/dart/explore/service/StationServiceImpl.java
Fixed workflow testing
reverted spring boot back to 3.0.6. I can't tell why all the tests are failing after the update, so I'm going to revert it back
closes #163
> Set up /all route and -

- src/main/java/com/dart/explore/controller/ReadController.java
- src/main/java/com/dart/explore/service/StationService.java
- src/main/java/com/dart/explore/service/StationServiceImpl.java
> Can get multiple POI from their IDs

- pom.xml
- src/main/java/com/dart/explore/config/OpenApiConfig.java
- src/main/java/com/dart/explore/controller/DatabaseController.java
- src/main/java/com/dart/explore/controller/ReadController.java
- src/main/java/com/dart/explore/security/ApiKeyFilter.java
- src/main/java/com/dart/explore/service/PointOfInterestService.java
> Swagger implemented and all routes well presented

- src/main/java/com/dart/explore/controller/ReadController.java
- src/main/java/com/dart/explore/repository/PointOfInterestRepository.java
- src/main/java/com/dart/explore/repository/StationRepository.java
- src/main/java/com/dart/explore/service/StationService.java
- src/main/java/com/dart/explore/service/StationServiceImpl.java
- src/test/java/com/dart/explore/integration/PointOfInterestRepositoryIT.java
- src/test/java/com/dart/explore/integration/StationRepositoryIT.java
> Updated routes to adhere more to spec talked about in #128

- src/main/java/com/dart/explore/controller/ReadController.java
- src/main/java/com/dart/explore/service/AmenityService.java
> created /amenities which returns all possible amenities

- .gitignore
- src/main/resources/scripts/apiCalls.js
- src/main/resources/scripts/package.json
> Created NodeJS script to populate test database.

- src/main/java/com/dart/explore/controller/ReadController.java
> Added CrossOrigin annotation.

- src/main/java/com/dart/explore/controller/DatabaseController.java
- src/main/java/com/dart/explore/controller/ReadController.java
- src/main/java/com/dart/explore/service/AmenityService.java
- src/main/java/com/dart/explore/service/PointOfInterestService.java
> Refactored delete operations to use IDs.

- src/main/java/com/dart/explore/dto/PointOfInterestDTO.java
- src/main/java/com/dart/explore/service/PointOfInterestService.java
> Properly making sure amenity exists during POI creation.

- src/main/java/com/dart/explore/controller/ReadController.java
> Refactored routes with optional amenities to use RequestParam instead.

- src/main/resources/scripts/apiCalls.js
> Using environment variable. Fixed leak.

- src/main/java/com/dart/explore/controller/ReadController.java
> Made amenitiesString required and fixed related bug with empty string.

- src/main/java/com/dart/explore/dto/PointOfInterestDTO.java
> Added stationName to POI DTO.

- README.md
- pom.xml
- src/main/java/com/dart/explore/config/OpenApiConfig.java
- src/main/java/com/dart/explore/service/PointOfInterestService.java
> Basic cleaning for Swagger, README, and pom.xml

- src/main/java/com/dart/explore/controller/ReadController.java
- src/main/java/com/dart/explore/repository/PointOfInterestRepository.java
- src/main/java/com/dart/explore/service/PointOfInterestService.java
Closes #185. @ZaneBartlett1, like you mentioned it would be good to put this on its own table eventually. Otherwise we might be doing a full table scan to get that info.
> Added route to get all types.

- src/main/java/com/dallasbymetro/backend/security/SecurityConfig.java
If it works, this would close issue #201
> removed http

- src/main/java/com/dallasbymetro/backend/controller/ReadController.java
- src/main/java/com/dallasbymetro/backend/repository/PointOfInterestRepository.java
- src/main/java/com/dallasbymetro/backend/service/StationService.java
- src/main/java/com/dallasbymetro/backend/service/StationServiceImpl.java
- src/main/resources/scripts/apiCalls.js
- src/test/java/com/dallasbymetro/backend/integration/PointOfInterestRepositoryIT.java
> Empty Amenity input to poi/amenity now returns all POIs.

- src/main/java/com/dallasbymetro/backend/controller/ReadController.java
- src/main/java/com/dallasbymetro/backend/dto/StationDTO.java
- src/main/java/com/dallasbymetro/backend/repository/PointOfInterestRepository.java
- src/main/java/com/dallasbymetro/backend/repository/StationRepository.java
- src/main/java/com/dallasbymetro/backend/service/PointOfInterestService.java
- src/main/java/com/dallasbymetro/backend/service/StationService.java
- src/main/java/com/dallasbymetro/backend/service/StationServiceImpl.java
- src/main/java/com/dallasbymetro/backend/utility/Pair.java
- src/main/resources/scripts/apiCalls.js
> Added /station route

- src/main/java/com/dallasbymetro/backend/controller/DatabaseController.java
- src/main/java/com/dallasbymetro/backend/controller/ReadController.java
- src/main/java/com/dallasbymetro/backend/exception/ElementNotFoundException.java
- src/main/java/com/dallasbymetro/backend/service/AmenityService.java
- src/main/java/com/dallasbymetro/backend/service/PointOfInterestService.java
- src/main/java/com/dallasbymetro/backend/service/StationService.java
- src/main/java/com/dallasbymetro/backend/service/StationServiceImpl.java
- src/main/java/com/dallasbymetro/backend/utility/ExceptionControllerAdvice.java
Closes #210. Previous branch to resolve this issue had some errors.
> Issue#210corrected

- src/main/java/com/dallasbymetro/backend/security/SecurityConfig.java
- src/main/resources/application-dev.properties
- src/main/resources/application-prod.properties
- src/main/resources/scripts/apiCalls.js
> Fixed CORs error for local development

- src/main/java/com/dallasbymetro/backend/controller/ReadController.java
- src/main/java/com/dallasbymetro/backend/service/AmenityService.java
> getAllAmenities to use Amenity DTO

- src/main/java/com/dallasbymetro/backend/dto/StationDTO.java
> added lat and long to StationDTO

- src/main/java/com/dallasbymetro/backend/service/StationServiceImpl.java
> Includes current station correctly

- .gitignore
- src/main/resources/upload_script/data.csv
- src/main/resources/upload_script/index.js
> Fixed bugs in issue.

- src/main/java/com/dallasbymetro/backend/service/StationServiceImpl.java
> Sort by connection distance
